// Generic category list for the word game.
const CATEGORIES = [
  "Animals", "Types of Cheese", "Countries", "Fruits", "Vegetables",
  "Movies", "TV Shows", "Superheroes", "Video Games", "Board Games",
  "Colors", "Car Brands", "Sports", "Musical Instruments", "Boy Names",
  "Girl Names", "Cities", "US States", "Rivers", "Mountains",
  "Types of Trees", "Flowers", "Insects", "Fish", "Birds",
  "Dog Breeds", "Cat Breeds", "Types of Pasta", "Desserts", "Candy",
  "Breakfast Foods", "Fast Food Chains", "Restaurants", "Drinks", "Cocktails",
  "Ice Cream Flavors", "Pizza Toppings", "Sandwiches", "Soups", "Spices",
  "Kitchen Appliances", "Tools", "School Subjects", "Jobs / Occupations", "Body Parts",
  "Clothing Items", "Shoe Brands", "Fashion Designers", "Colors of Paint", "Things That Are Cold",
  "Things That Are Hot", "Things in a Kitchen", "Things in a Bathroom", "Things in a Classroom", "Things at the Beach",
  "Things in Space", "Planets", "Things That Fly", "Things That Are Round", "Things That Are Sticky",
  "Cartoon Characters", "Disney Movies", "Disney Characters", "Pixar Movies", "Actors",
  "Actresses", "Musicians", "Bands", "Songs", "Dance Moves",
  "Authors", "Book Titles", "Fairy Tales", "Mythical Creatures", "Greek Gods",
  "Superpowers", "Villains", "Halloween Costumes", "Holidays", "Christmas Traditions",
  "Wedding Words", "Birthday Party Words", "Things You Wrap", "Things That Are Striped", "Things That Are Furry",
  "Types of Weather", "Seasons", "Camping Gear", "Sports Equipment", "Olympic Sports",
  "Card Games", "Playground Equipment", "Toys", "Board Game Pieces", "App Names",
  "Websites", "Emojis (describe one)", "Social Media Platforms", "TV Networks", "Cartoon Networks Shows",
  "Comic Books", "Magic Spells", "Star Wars Characters", "Harry Potter Words", "Marvel Characters",
  "Video Game Consoles", "Sports Teams", "NBA Teams", "NFL Teams", "Countries in Europe",
  "Countries in Africa", "Languages", "Capital Cities", "Islands", "Deserts",
  "Oceans and Seas", "Types of Weather Disasters", "Modes of Transportation", "Types of Boats", "Types of Trucks",
  "Motorcycle Brands", "Airlines", "Things at an Airport", "Things in a Hospital", "Medical Terms",
  "Things a Doctor Uses", "Types of Doctors", "School Supplies", "Things in a Backpack", "Musical Genres",
  "Dances", "Yoga Poses", "Exercises", "Gym Equipment", "Things That Are Loud",
  "Things That Are Quiet", "Things You Recycle", "Things Made of Metal", "Things Made of Wood", "Things Made of Glass",
  "Things in a Garage", "Power Tools", "Things That Spin", "Things With Wheels", "Things That Glow",
  "Nursery Rhymes", "Board Games for Kids", "Things at a Circus", "Zoo Animals", "Farm Animals",
  "Ocean Animals", "Animals with Stripes", "Animals with Spots", "Nocturnal Animals", "Animals in Australia",
  "Dinosaurs", "Extinct Animals", "Bugs", "Reptiles", "Amphibians",
  "Types of Nuts", "Types of Beans", "Salad Ingredients", "Sauces and Condiments", "Types of Bread",
  "Things You Bake", "Cake Flavors", "Cookie Types", "Chocolate Brands", "Chip Brands",
  "Cereal Brands", "Soda Brands", "Coffee Drinks", "Tea Types", "Smoothie Ingredients",

  // Creative / silly prompts
  "Things You'd Find in a Pirate's Treasure Chest", "Reasons to Be Late for Work", "Things That Are Embarrassing to Admit",
  "Superhero Sidekicks", "Types of Laughter", "Things You Shout at a Sports Game", "Excuses for Not Doing Homework",
  "Things Grandparents Say", "Things You'd Pack for a Road Trip", "One-Hit Wonders", "Things That Make You Sneeze",
  "Words That Rhyme with 'Day'", "Board Game Villains", "Things in a Wizard's Bag", "Halloween Candy",
  "Things You Do Before Bed", "Reality TV Shows", "Things at a Wedding", "Superstitions", "Things That Squeak",
  "Karaoke Songs", "Things You Find Under a Couch Cushion", "Ways to Say Goodbye", "Things That Are Slippery",
  "Party Games", "Things a Ninja Uses", "Pirate Words", "Things You'd Find in a Treehouse", "Slang for Money",
  "Types of Hats", "Things You Do at a Sleepover", "Excuses for Being Messy", "Things That Come in Pairs",
  "Things a Superhero Wears", "Things You'd Find in Santa's Workshop", "Words for 'Big'", "Words for 'Small'",
  "Things That Bounce", "Things You'd Bring to a Desert Island", "Reasons to Cancel Plans", "Things That Are Sour",
  "Things That Are Spicy", "Things You Find at a Farmers Market", "Things in a First-Aid Kit", "Types of Dances at a Wedding",
  "Things You'd Find in a Time Capsule", "Villain Lairs", "Things a Robot Can Do", "Video Game Power-Ups",
  "Things That Are Sharp", "Things You'd Find in a Toolbox", "Things a Mermaid Might Own", "Things You Whisper",
  "Things You'd Yell in an Emergency", "Things That Are Fluffy", "Things You'd Find at a Carnival", "Circus Acts",
  "Things a Superhero Needs to Fight Crime", "Things You'd Find in a Fridge", "Things You'd Find in a Freezer",
  "Ways to Cook an Egg", "Things You'd Find on a Farm", "Things You'd Find in a Jungle", "Things You'd Find in the Arctic",
  "Things That Are Expensive", "Things That Are Cheap", "Things You Haggle For", "Things You'd Find at a Yard Sale",
  "Reasons to Call in Sick", "Things You'd Find in Grandma's Purse", "Things a Baby Does", "Things Toddlers Say",
  "Things You'd Find at Recess", "Playground Games", "Things You'd Do on a Rainy Day", "Things You'd Do on a Snow Day",
  "Types of Selfies", "Things People Post on Social Media", "Things That Go Viral", "Internet Memes",
  "Things You'd Say to a Genie", "Wishes You'd Make", "Things a Dragon Guards", "Types of Knights",
  "Things a Detective Uses", "Mystery Movie Clichés", "Things That Creak", "Haunted House Features",
  "Scary Movie Monsters", "Things That Glow in the Dark", "Camping Fears", "Things You'd Bring Camping",
  "Road Trip Games", "Things You See on a Road Trip", "Things at a Gas Station", "Things at a Rest Stop",
  "Things a Chef Says", "Cooking Show Phrases", "Things That Burn Easily", "Kitchen Disasters",
  "Things a Waiter Says", "Restaurant Complaints", "Things on a Menu", "Fancy Restaurant Words",
  "Things You'd Say to a Baby", "Lullabies", "Bedtime Story Characters", "Things Under a Kid's Bed",
  "Imaginary Friends", "Things a Clown Does", "Things at a Rodeo", "Cowboy Words", "Wild West Words",
  "Things an Astronaut Needs", "Space Movie Titles", "Alien Names", "Things on the Moon",
  "Things a Scuba Diver Sees", "Deep Sea Creatures", "Things in a Coral Reef", "Pirate Ship Parts",
  "Things a Lifeguard Watches For", "Pool Games", "Water Park Rides", "Things at a Beach Party",
  "Summer Activities", "Winter Activities", "Spring Chores", "Fall Traditions", "Things You Do on New Year's Eve",
  "Valentine's Day Gifts", "Mother's Day Gifts", "Father's Day Gifts", "Graduation Gifts", "Baby Shower Gifts",
  "Things You Regift", "Worst Gifts to Receive", "Things in a Gift Basket", "Things You'd Find in a Piñata",
];
