// Generic category list for the word game.
const CATEGORIES = [
  "Animals", "Types of Cheese", "Countries", "Fruits", "Vegetables",
  "Movies", "TV Shows", "Superheroes", "Video Games", "Board Games",
  "Colors", "Car Brands", "Sports", "Musical Instruments", "Boy Names",
  "Girl Names", "Cities", "US States", "Rivers", "Mountains",
  "Types of Trees", "Flowers", "Insects", "Fish", "Birds",
  "Dog Breeds", "Cat Breeds", "Types of Pasta", "Desserts", "Candy",
  "Breakfast Foods", "Fast Food Chains", "Restaurants", "Drinks", "Cocktails",
  "Ice Cream Flavors", "Pizza Toppings", "Sandwiches", "Soups", "Spices",
  "Kitchen Appliances", "Tools", "School Subjects", "Jobs / Occupations", "Body Parts",
  "Clothing Items", "Shoe Brands", "Fashion Designers", "Colors of Paint", "Things That Are Cold",
  "Things That Are Hot", "Things in a Kitchen", "Things in a Bathroom", "Things in a Classroom", "Things at the Beach",
  "Things in Space", "Planets", "Things That Fly", "Things That Are Round", "Things That Are Sticky",
  "Cartoon Characters", "Disney Movies", "Disney Characters", "Pixar Movies", "Actors",
  "Actresses", "Musicians", "Bands", "Songs", "Dance Moves",
  "Authors", "Book Titles", "Fairy Tales", "Mythical Creatures", "Greek Gods",
  "Superpowers", "Villains", "Halloween Costumes", "Holidays", "Christmas Traditions",
  "Wedding Words", "Birthday Party Words", "Things You Wrap", "Things That Are Striped", "Things That Are Furry",
  "Types of Weather", "Seasons", "Camping Gear", "Sports Equipment", "Olympic Sports",
  "Card Games", "Playground Equipment", "Toys", "Board Game Pieces", "App Names",
  "Websites", "Emojis (describe one)", "Social Media Platforms", "TV Networks", "Cartoon Networks Shows",
  "Comic Books", "Magic Spells", "Star Wars Characters", "Harry Potter Words", "Marvel Characters",
  "Video Game Consoles", "Sports Teams", "NBA Teams", "NFL Teams", "Countries in Europe",
  "Countries in Africa", "Languages", "Capital Cities", "Islands", "Deserts",
  "Oceans and Seas", "Types of Weather Disasters", "Modes of Transportation", "Types of Boats", "Types of Trucks",
  "Motorcycle Brands", "Airlines", "Things at an Airport", "Things in a Hospital", "Medical Terms",
  "Things a Doctor Uses", "Types of Doctors", "School Supplies", "Things in a Backpack", "Musical Genres",
  "Dances", "Yoga Poses", "Exercises", "Gym Equipment", "Things That Are Loud",
  "Things That Are Quiet", "Things You Recycle", "Things Made of Metal", "Things Made of Wood", "Things Made of Glass",
  "Things in a Garage", "Power Tools", "Things That Spin", "Things With Wheels", "Things That Glow",
  "Nursery Rhymes", "Board Games for Kids", "Things at a Circus", "Zoo Animals", "Farm Animals",
  "Ocean Animals", "Animals with Stripes", "Animals with Spots", "Nocturnal Animals", "Animals in Australia",
  "Dinosaurs", "Extinct Animals", "Bugs", "Reptiles", "Amphibians",
  "Types of Nuts", "Types of Beans", "Salad Ingredients", "Sauces and Condiments", "Types of Bread",
  "Things You Bake", "Cake Flavors", "Cookie Types", "Chocolate Brands", "Chip Brands",
  "Cereal Brands", "Soda Brands", "Coffee Drinks", "Tea Types", "Smoothie Ingredients",
];
